# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/Progi/praktika1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/Progi/praktika1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Progi/praktika1/CMakeFiles /mnt/d/Progi/praktika1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Progi/praktika1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

Casino_realization.o: Casino_realization.cpp.o

.PHONY : Casino_realization.o

# target to build an object file
Casino_realization.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Casino_realization.cpp.o
.PHONY : Casino_realization.cpp.o

Casino_realization.i: Casino_realization.cpp.i

.PHONY : Casino_realization.i

# target to preprocess a source file
Casino_realization.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Casino_realization.cpp.i
.PHONY : Casino_realization.cpp.i

Casino_realization.s: Casino_realization.cpp.s

.PHONY : Casino_realization.s

# target to generate assembly for a file
Casino_realization.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Casino_realization.cpp.s
.PHONY : Casino_realization.cpp.s

Dice_realisation.o: Dice_realisation.cpp.o

.PHONY : Dice_realisation.o

# target to build an object file
Dice_realisation.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Dice_realisation.cpp.o
.PHONY : Dice_realisation.cpp.o

Dice_realisation.i: Dice_realisation.cpp.i

.PHONY : Dice_realisation.i

# target to preprocess a source file
Dice_realisation.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Dice_realisation.cpp.i
.PHONY : Dice_realisation.cpp.i

Dice_realisation.s: Dice_realisation.cpp.s

.PHONY : Dice_realisation.s

# target to generate assembly for a file
Dice_realisation.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Dice_realisation.cpp.s
.PHONY : Dice_realisation.cpp.s

Game_realization.o: Game_realization.cpp.o

.PHONY : Game_realization.o

# target to build an object file
Game_realization.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Game_realization.cpp.o
.PHONY : Game_realization.cpp.o

Game_realization.i: Game_realization.cpp.i

.PHONY : Game_realization.i

# target to preprocess a source file
Game_realization.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Game_realization.cpp.i
.PHONY : Game_realization.cpp.i

Game_realization.s: Game_realization.cpp.s

.PHONY : Game_realization.s

# target to generate assembly for a file
Game_realization.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Game_realization.cpp.s
.PHONY : Game_realization.cpp.s

Hostandplayers.o: Hostandplayers.cpp.o

.PHONY : Hostandplayers.o

# target to build an object file
Hostandplayers.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Hostandplayers.cpp.o
.PHONY : Hostandplayers.cpp.o

Hostandplayers.i: Hostandplayers.cpp.i

.PHONY : Hostandplayers.i

# target to preprocess a source file
Hostandplayers.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Hostandplayers.cpp.i
.PHONY : Hostandplayers.cpp.i

Hostandplayers.s: Hostandplayers.cpp.s

.PHONY : Hostandplayers.s

# target to generate assembly for a file
Hostandplayers.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Hostandplayers.cpp.s
.PHONY : Hostandplayers.cpp.s

Roulete_realisation.o: Roulete_realisation.cpp.o

.PHONY : Roulete_realisation.o

# target to build an object file
Roulete_realisation.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Roulete_realisation.cpp.o
.PHONY : Roulete_realisation.cpp.o

Roulete_realisation.i: Roulete_realisation.cpp.i

.PHONY : Roulete_realisation.i

# target to preprocess a source file
Roulete_realisation.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Roulete_realisation.cpp.i
.PHONY : Roulete_realisation.cpp.i

Roulete_realisation.s: Roulete_realisation.cpp.s

.PHONY : Roulete_realisation.s

# target to generate assembly for a file
Roulete_realisation.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/Roulete_realisation.cpp.s
.PHONY : Roulete_realisation.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... Casino_realization.o"
	@echo "... Casino_realization.i"
	@echo "... Casino_realization.s"
	@echo "... Dice_realisation.o"
	@echo "... Dice_realisation.i"
	@echo "... Dice_realisation.s"
	@echo "... Game_realization.o"
	@echo "... Game_realization.i"
	@echo "... Game_realization.s"
	@echo "... Hostandplayers.o"
	@echo "... Hostandplayers.i"
	@echo "... Hostandplayers.s"
	@echo "... Roulete_realisation.o"
	@echo "... Roulete_realisation.i"
	@echo "... Roulete_realisation.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

